 
FROM dungpb/dira_ros:ros-python-tensorflow

# WORKDIR /app

RUN pip install opencv-contrib-python tensorflow-gpu==1.14.0 keras dlib
                                                                                                                                                                                                                                                                                                                                                                       
